### ISSUE TITLE
BaileysError: Unexpected error in login

### ISSUE THREAD

**Issue by Cyphexd** [ShinNouzen/Chitoge#38]
After starting i got following error

`/home/pex/bots/dev/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97
            throw new Constants_1.BaileysError(`Unexpected error in login`, { response, status: response.status });
                  ^

BaileysError: Unexpected error in login
    at WAClient.authenticate (/home/pex/bots/dev/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebSocket.<anonymous> (/home/pex/bots/dev/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:107:40) {
  status: 401,
  context: { response: { status: 401 }, status: 401 }
}`

**Comment by LuckyYam** [comment]
You're using MD version of WhatsApp

**Comment by Cyphexd** [comment]
> You're using MD version of WhatsApp

What do you mean with MD version ?

**Comment by Cyphexd** [comment]
nevermind got it
